### ISSUE TITLE
Where to put macros go in your package outline template?

### ISSUE THREAD

**Issue by doolio** [alphapapa/emacs-package-dev-handbook#19]
Do you recommend they have their own dedicated section - if so after which current section? Or perhaps they should be in a subsection under `;;;; Functions`? Thanks for your time.

**Comment by alphapapa** [comment]
Hello,

Generally macros should come before functions, since they'll likely be needed in some function definitions.  I generally put the macros after the `defvar`s and `defcustoms`, but if a macro is used in one of those definitions, it will need to be moved.  You can use my https://github.com/alphapapa/makem.sh script to easily lint compilation to catch problems like that.

**Comment by doolio** [comment]
Thanks for the quick reply!

**Comment by doolio** [comment]
Sorry, and that goes for `define-minor-mode` expressions too which if I'm not mistaken is a macro but I often see it put at the very end of a `.el` file?

**Comment by alphapapa** [comment]
You can put those wherever seems appropriate and works correctly.
