### ISSUE TITLE
[Question] defun order

### ISSUE THREAD

**Issue by doolio** [alphapapa/emacs-package-dev-handbook#24]
In your template example, you have the commands section before the functions section. The example command calls each of the example functions. Should a function that is called be placed **after** the command/function that call it? Thanks for your time.

```emacs-lisp
;;;; Commands

;;;###autoload
(defun package-name-command (args)
  "Frobnicate the flange."
  (interactive)
  (package-name-foo
   (package-name--bar args)))

;;;; Functions

;;;;; Public

(defun package-name-foo (args)
  "Return foo for ARGS."
  (foo args))

;;;;; Private

(defun package-name--bar (args)
  "Return bar for ARGS."
  (bar args))
```

**Comment by alphapapa** [comment]
Functions, including interactive commands, can be defined in any order, because they aren't called until runtime, after they have been defined and interned in the obarray.  Macros must be defined before they are called, because the byte-compiler must be able to call them at expansion/compilation time.  You can use my makem.sh script to catch these kinds of errors: https://github.com/alphapapa/makem.sh  `flymake` also helps with that.

**Comment by doolio** [comment]
Thank you. Super informative as always.
